version: "2"
linters:
  # disable:
  #   - foo
  #   - bar
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1000' # Incorrect or missing package comment [https://staticcheck.dev/docs/checks#ST1000]
        - '-ST1003' # Poorly chosen identifier             [https://staticcheck.dev/docs/checks#ST1003]
        - '-ST1006' # Poorly chosen receiver name          [https://staticcheck.dev/docs/checks#ST1006]
