version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - depguard
    - dupword
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - inamedparam
    - ireturn
    - lll
    - mnd
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - recvcheck
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1000' # Incorrect or missing package comment [https://staticcheck.dev/docs/checks#ST1000]
        - '-ST1003' # Poorly chosen identifier             [https://staticcheck.dev/docs/checks#ST1003]
        - '-ST1006' # Poorly chosen receiver name          [https://staticcheck.dev/docs/checks#ST1006]
formatters:
  enable:
    - gofumpt
