services:
  app:
    restart: unless-stopped
    image: lighthouse_app
    env_file: .env.prod
    network_mode: host
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: /app/healthcheck
      interval: 30s
      timeout: 5s
      retries: 2
