version: '3'
services:
  app:
    restart: unless-stopped
    image: lighthouse_app
    env_file: .env.prod
    network_mode: host
    volumes:
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock:ro
      - ./logs:/app/logs
